# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: 'Upload Cucumber to Zephyr Scale'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B verify --file pom.xml
      continue-on-error: true
    - name: Sending result to Zephyr Scale API
      run: |
        curl -X POST https://c4j.cucumber.io/ci/rest/api/results \
        -H 'authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjb20uc21hcnRiZWFyLmN1Y3VtYmVyIiwiYXVkIjoiY2kiLCJjb250ZXh0Ijp7ImxpdmluZ19kb2NfaWQiOjMwNzd9LCJpYXQiOjE2NTIzNjg4MTl9.YcNfnJUbvQvugnGMAA8diKJEP2pbQr49WQlun5jACug' \
        -H 'content-type: multipart/form-data' \
        -F 'results_files'=@cucumber.json \
        -F language=jvm
      shell: bash
